### ISSUE TITLE
Cannot see files,contact nor bookmark

### ISSUE THREAD

**Issue by joeitu** [inrupt/pod-browser#391] opened 2021-11-19 11:54 UTC
Hello,

I tried to browse my pod hosted on https://solidcommunity.net on https://pod-browser.vercel.app/

```
Failed to load resource: the server responded with a status of 403 ()
https://o431832.ingest.sentry.io/api/5383681/envelope/?sentry_key=1291ab8c6a364f9791060107a9bf7ebd&sentry_version=7
```

Testedon chromium without any extenssion
```
Chromium
Version 95.0.4638.69 (Official Build) snap (64-bit)
```

**Comment by nicolasmondada** [comment] 2021-11-19 12:25
Hi @joeitu,

I'm not sure where you got the vercel.app url from but it's not the right one for Pod Browser. Could you please try again on https://podbrowser.inrupt.com/? 

Cheers,
Nick.-

**Comment by joeitu** [comment] 2021-11-19 12:32
Don't remember either :s

I tried on podbrowser.inrupt.com/ and the same result, but with a different error:
```
_error.jsx:26 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'statusCode')
    at _error.jsx:26
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at n (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at _error.jsx:26
    at H (react-dom.production.min.js:27)
    at Q (react-dom.production.min.js:29)
    at ou (react-dom.production.min.js:216)
    at Ei (react-dom.production.min.js:248)
    at xi (react-dom.production.min.js:250)
    at vi (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wl (react-dom.production.min.js:122)
    at Ql (react-dom.production.min.js:123)
    at Hl (react-dom.production.min.js:122)
    at fi (react-dom.production.min.js:237)
    at Gi (react-dom.production.min.js:285)
    at rs (react-dom.production.min.js:289)
    at Object.t.render (react-dom.production.min.js:296)
    at v.default.createElement.callbacks (index.js:61)
    at ye (index.js:81)
    at index.js:59
```

**Comment by ThisIsMissEm** [comment] 2022-03-23 13:18
@joeitu could you retest, Sentry shouldn't have been the root cause of the issue here; but I was able to login using a solidcommunity.net account & pod yesterday, if this isn't still an issue then we'd be able to close this.

**Comment by joeitu** [comment] 2022-03-23 13:21
Yes, it works now, can be closed

**Closed** 2022-03-23 14:09 UTC
